name: Feature Request
description: Suggest your preferred flavour of improvement!
labels: [ "feature" ]
body:
  - type: input
    attributes:
      label: Summary
      description: A concise, specific description of what the improvement is
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe the solution you'd like"
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Describe alternatives you've considered"
  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: "A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]"
  - type: textarea
    attributes:
      label: Anything Else?
      description: Add any other context or screenshots about the feature request here.
